// =====================================================
// AFRO SENTINEL WATCHTOWER - Constants & Types
// =====================================================

export const PRIORITIES = {
  P1: { label: 'Critical', color: 'priority-p1', description: 'Immediate threat - requires urgent attention' },
  P2: { label: 'High', color: 'priority-p2', description: 'Significant threat - respond within hours' },
  P3: { label: 'Medium', color: 'priority-p3', description: 'Moderate concern - monitor closely' },
  P4: { label: 'Low', color: 'priority-p4', description: 'Low concern - routine monitoring' },
} as const;

export const SOURCE_TIERS = {
  tier_1: { label: 'TIER 1', description: 'Official & Institutional', color: 'tier-1', examples: ['WHO', 'Africa CDC', 'ProMED', 'National Health Ministries'] },
  tier_2: { label: 'TIER 2', description: 'Media & News', color: 'tier-2', examples: ['Reuters', 'BBC', 'Al Jazeera', 'AllAfrica'] },
  tier_3: { label: 'TIER 3', description: 'Community & Social', color: 'tier-3', examples: ['X/Twitter', 'Facebook', 'WhatsApp', 'Community Radio'] },
} as const;

export const DISEASE_CATEGORIES = {
  vhf: { label: 'Viral Hemorrhagic Fever', icon: '🩸', color: 'destructive' },
  respiratory: { label: 'Respiratory', icon: '🫁', color: 'primary' },
  enteric: { label: 'Enteric/Diarrheal', icon: '💧', color: 'accent' },
  vector_borne: { label: 'Vector-Borne', icon: '🦟', color: 'sunset' },
  zoonotic: { label: 'Zoonotic', icon: '🦇', color: 'terracotta' },
  vaccine_preventable: { label: 'Vaccine-Preventable', icon: '💉', color: 'savanna' },
  environmental: { label: 'Environmental', icon: '🌍', color: 'sahara' },
  unknown: { label: 'Unknown/Other', icon: '❓', color: 'muted' },
} as const;

export const SIGNAL_STATUSES = {
  new: { label: 'New', description: 'Freshly ingested, awaiting triage' },
  triaged: { label: 'Triaged', description: 'Initial assessment complete' },
  validated: { label: 'Validated', description: 'Confirmed and verified' },
  dismissed: { label: 'Dismissed', description: 'False positive or irrelevant' },
} as const;

// African Countries with ISO-3 codes for map integration
export const AFRO_COUNTRIES = [
  { code: 'AGO', name: 'Angola', region: 'Southern', lat: -11.2027, lng: 17.8739 },
  { code: 'BEN', name: 'Benin', region: 'West', lat: 9.3077, lng: 2.3158 },
  { code: 'BWA', name: 'Botswana', region: 'Southern', lat: -22.3285, lng: 24.6849 },
  { code: 'BFA', name: 'Burkina Faso', region: 'West', lat: 12.2383, lng: -1.5616 },
  { code: 'BDI', name: 'Burundi', region: 'East', lat: -3.3731, lng: 29.9189 },
  { code: 'CPV', name: 'Cabo Verde', region: 'West', lat: 16.5388, lng: -23.0418 },
  { code: 'CMR', name: 'Cameroon', region: 'Central', lat: 7.3697, lng: 12.3547 },
  { code: 'CAF', name: 'Central African Republic', region: 'Central', lat: 6.6111, lng: 20.9394 },
  { code: 'TCD', name: 'Chad', region: 'Central', lat: 15.4542, lng: 18.7322 },
  { code: 'COM', name: 'Comoros', region: 'East', lat: -11.6455, lng: 43.3333 },
  { code: 'COG', name: 'Congo', region: 'Central', lat: -0.228, lng: 15.8277 },
  { code: 'CIV', name: "Côte d'Ivoire", region: 'West', lat: 7.54, lng: -5.5471 },
  { code: 'COD', name: 'DR Congo', region: 'Central', lat: -4.0383, lng: 21.7587 },
  { code: 'DJI', name: 'Djibouti', region: 'East', lat: 11.8251, lng: 42.5903 },
  { code: 'EGY', name: 'Egypt', region: 'North', lat: 26.8206, lng: 30.8025 },
  { code: 'GNQ', name: 'Equatorial Guinea', region: 'Central', lat: 1.6508, lng: 10.2679 },
  { code: 'ERI', name: 'Eritrea', region: 'East', lat: 15.1794, lng: 39.7823 },
  { code: 'SWZ', name: 'Eswatini', region: 'Southern', lat: -26.5225, lng: 31.4659 },
  { code: 'ETH', name: 'Ethiopia', region: 'East', lat: 9.145, lng: 40.4897 },
  { code: 'GAB', name: 'Gabon', region: 'Central', lat: -0.8037, lng: 11.6094 },
  { code: 'GMB', name: 'Gambia', region: 'West', lat: 13.4432, lng: -15.3101 },
  { code: 'GHA', name: 'Ghana', region: 'West', lat: 7.9465, lng: -1.0232 },
  { code: 'GIN', name: 'Guinea', region: 'West', lat: 9.9456, lng: -9.6966 },
  { code: 'GNB', name: 'Guinea-Bissau', region: 'West', lat: 11.8037, lng: -15.1804 },
  { code: 'KEN', name: 'Kenya', region: 'East', lat: -0.0236, lng: 37.9062 },
  { code: 'LSO', name: 'Lesotho', region: 'Southern', lat: -29.61, lng: 28.2336 },
  { code: 'LBR', name: 'Liberia', region: 'West', lat: 6.4281, lng: -9.4295 },
  { code: 'LBY', name: 'Libya', region: 'North', lat: 26.3351, lng: 17.2283 },
  { code: 'MDG', name: 'Madagascar', region: 'East', lat: -18.7669, lng: 46.8691 },
  { code: 'MWI', name: 'Malawi', region: 'Southern', lat: -13.2543, lng: 34.3015 },
  { code: 'MLI', name: 'Mali', region: 'West', lat: 17.5707, lng: -3.9962 },
  { code: 'MRT', name: 'Mauritania', region: 'West', lat: 21.0079, lng: -10.9408 },
  { code: 'MUS', name: 'Mauritius', region: 'East', lat: -20.3484, lng: 57.5522 },
  { code: 'MAR', name: 'Morocco', region: 'North', lat: 31.7917, lng: -7.0926 },
  { code: 'MOZ', name: 'Mozambique', region: 'Southern', lat: -18.6657, lng: 35.5296 },
  { code: 'NAM', name: 'Namibia', region: 'Southern', lat: -22.9576, lng: 18.4904 },
  { code: 'NER', name: 'Niger', region: 'West', lat: 17.6078, lng: 8.0817 },
  { code: 'NGA', name: 'Nigeria', region: 'West', lat: 9.082, lng: 8.6753 },
  { code: 'RWA', name: 'Rwanda', region: 'East', lat: -1.9403, lng: 29.8739 },
  { code: 'STP', name: 'Sao Tome and Principe', region: 'Central', lat: 0.1864, lng: 6.6131 },
  { code: 'SEN', name: 'Senegal', region: 'West', lat: 14.4974, lng: -14.4524 },
  { code: 'SYC', name: 'Seychelles', region: 'East', lat: -4.6796, lng: 55.492 },
  { code: 'SLE', name: 'Sierra Leone', region: 'West', lat: 8.4606, lng: -11.7799 },
  { code: 'SOM', name: 'Somalia', region: 'East', lat: 5.1521, lng: 46.1996 },
  { code: 'ZAF', name: 'South Africa', region: 'Southern', lat: -30.5595, lng: 22.9375 },
  { code: 'SSD', name: 'South Sudan', region: 'East', lat: 6.877, lng: 31.307 },
  { code: 'SDN', name: 'Sudan', region: 'North', lat: 12.8628, lng: 30.2176 },
  { code: 'TZA', name: 'Tanzania', region: 'East', lat: -6.369, lng: 34.8888 },
  { code: 'TGO', name: 'Togo', region: 'West', lat: 8.6195, lng: 0.8248 },
  { code: 'TUN', name: 'Tunisia', region: 'North', lat: 33.8869, lng: 9.5375 },
  { code: 'UGA', name: 'Uganda', region: 'East', lat: 1.3733, lng: 32.2903 },
  { code: 'ZMB', name: 'Zambia', region: 'Southern', lat: -13.1339, lng: 27.8493 },
  { code: 'ZWE', name: 'Zimbabwe', region: 'Southern', lat: -19.0154, lng: 29.1549 },
  { code: 'DZA', name: 'Algeria', region: 'North', lat: 28.0339, lng: 1.6596 },
] as const;

// WHO AFRO Disease Registry
export const AFRO_DISEASES = [
  { code: 'A00', name: 'Cholera', syndrome: 'AWD', category: 'enteric' as const },
  { code: 'A01', name: 'Typhoid fever', syndrome: 'Febrile', category: 'enteric' as const },
  { code: 'A20', name: 'Plague', syndrome: 'Febrile', category: 'zoonotic' as const },
  { code: 'A80', name: 'Polio', syndrome: 'AFP', category: 'vaccine_preventable' as const },
  { code: 'A90', name: 'Dengue', syndrome: 'Febrile', category: 'vector_borne' as const },
  { code: 'A92', name: 'Yellow fever', syndrome: 'Febrile', category: 'vhf' as const },
  { code: 'B50', name: 'Malaria', syndrome: 'Febrile', category: 'vector_borne' as const },
  { code: 'B05', name: 'Measles', syndrome: 'Rash', category: 'vaccine_preventable' as const },
  { code: 'A98', name: 'Viral hemorrhagic fevers', syndrome: 'Hemorrhagic', category: 'vhf' as const },
  { code: 'A99', name: 'Ebola/Marburg', syndrome: 'Hemorrhagic', category: 'vhf' as const },
  { code: 'U07', name: 'COVID-19', syndrome: 'Respiratory', category: 'respiratory' as const },
  { code: 'A82', name: 'Rabies', syndrome: 'Neurological', category: 'zoonotic' as const },
  { code: 'A39', name: 'Meningococcal disease', syndrome: 'Neurological', category: 'vaccine_preventable' as const },
  { code: 'A96', name: 'Lassa fever', syndrome: 'Hemorrhagic', category: 'vhf' as const },
  { code: 'MPOX', name: 'Mpox', syndrome: 'Rash', category: 'zoonotic' as const },
] as const;

// API Sources Registry - 16 Live Grassroots Sources (No API Keys Required)
export interface ApiSource {
  source_id: string;
  source_name: string;
  status: 'active' | 'inactive';
  base_url: string;
  documentation_url?: string;
  source_type: string;
  category: string;
  coverage: string;
  priority: number;
  auth_type: string;
  data_format: string;
}

export const API_SOURCES: ApiSource[] = [
  // =====================================================
  // TIER 1 - Official & Institutional Sources
  // =====================================================
  {
    source_id: 'GDELT-V2',
    source_name: 'GDELT Project 2.0',
    status: 'active',
    base_url: 'https://api.gdeltproject.org/api/v2/doc/doc',
    source_type: 'News Aggregator',
    category: 'Aggregator',
    coverage: 'Global',
    priority: 1,
    auth_type: 'None',
    data_format: 'JSON',
  },
  {
    source_id: 'WHO-GHO',
    source_name: 'WHO Global Health Observatory',
    status: 'active',
    base_url: 'https://ghoapi.azureedge.net/api/',
    source_type: 'Official API',
    category: 'Official',
    coverage: 'Global',
    priority: 1,
    auth_type: 'None',
    data_format: 'JSON',
  },
  {
    source_id: 'WHO-DON',
    source_name: 'WHO Disease Outbreak News',
    status: 'active',
    base_url: 'https://www.who.int/feeds/entity/csr/don/en/rss.xml',
    source_type: 'Official RSS',
    category: 'Official',
    coverage: 'Global',
    priority: 1,
    auth_type: 'None',
    data_format: 'RSS',
  },
  // NEW: WHO AFRO Weekly Bulletins
  {
    source_id: 'WHO-AFRO-BULLETIN',
    source_name: 'WHO AFRO Weekly Bulletins',
    status: 'active',
    base_url: 'https://www.afro.who.int/health-topics/disease-outbreaks/outbreaks-and-other-emergencies-updates',
    documentation_url: 'https://www.afro.who.int/health-topics/disease-outbreaks',
    source_type: 'Official RSS',
    category: 'Official',
    coverage: 'Africa',
    priority: 1,
    auth_type: 'None',
    data_format: 'RSS',
  },
  {
    source_id: 'AFRICA-CDC',
    source_name: 'Africa CDC',
    status: 'active',
    base_url: 'https://africacdc.org/feed/',
    source_type: 'Official RSS',
    category: 'Official',
    coverage: 'Africa',
    priority: 1,
    auth_type: 'None',
    data_format: 'RSS',
  },
  // NEW: Africa CDC EBS Reports
  {
    source_id: 'AFRICA-CDC-EBS',
    source_name: 'Africa CDC Event-Based Surveillance',
    status: 'active',
    base_url: 'https://africacdc.org/disease-outbreak/',
    documentation_url: 'https://africacdc.org/surveillance-and-disease-intelligence/',
    source_type: 'Official EBS',
    category: 'Official',
    coverage: 'Africa',
    priority: 1,
    auth_type: 'None',
    data_format: 'HTML/JSON',
  },
  {
    source_id: 'HDX',
    source_name: 'Humanitarian Data Exchange',
    status: 'active',
    base_url: 'https://data.humdata.org/api/3/action/',
    source_type: 'Official API',
    category: 'Humanitarian',
    coverage: 'Global',
    priority: 1,
    auth_type: 'None',
    data_format: 'JSON',
  },
  {
    source_id: 'RELIEF-WEB',
    source_name: 'ReliefWeb (UN OCHA)',
    status: 'active',
    base_url: 'https://api.reliefweb.int/v1/reports',
    source_type: 'Official API',
    category: 'Humanitarian',
    coverage: 'Global',
    priority: 1,
    auth_type: 'None',
    data_format: 'JSON',
  },
  {
    source_id: 'OCHA-FTS',
    source_name: 'OCHA Financial Tracking Service',
    status: 'active',
    base_url: 'https://api.hpc.tools/v1/public/fts/flow',
    source_type: 'Official API',
    category: 'Humanitarian',
    coverage: 'Global',
    priority: 1,
    auth_type: 'None',
    data_format: 'JSON',
  },
  {
    source_id: 'APO-AFRICA',
    source_name: 'APO Group Africa Newsroom',
    status: 'active',
    base_url: 'https://www.africa-newsroom.com/rss/',
    source_type: 'Press Releases',
    category: 'Official',
    coverage: 'Africa',
    priority: 1,
    auth_type: 'None',
    data_format: 'RSS',
  },
  
  // =====================================================
  // TIER 2 - Local Language Sources (GRASSROOTS)
  // =====================================================
  {
    source_id: 'BBC-HAUSA',
    source_name: 'BBC Hausa',
    status: 'active',
    base_url: 'https://feeds.bbci.co.uk/hausa/rss.xml',
    source_type: 'Local Language RSS',
    category: 'Local_Language',
    coverage: 'Nigeria, Niger, Cameroon',
    priority: 2,
    auth_type: 'None',
    data_format: 'RSS',
  },
  {
    source_id: 'BBC-SWAHILI',
    source_name: 'BBC Swahili',
    status: 'active',
    base_url: 'https://feeds.bbci.co.uk/swahili/rss.xml',
    source_type: 'Local Language RSS',
    category: 'Local_Language',
    coverage: 'Kenya, Tanzania, DRC, Uganda',
    priority: 2,
    auth_type: 'None',
    data_format: 'RSS',
  },
  {
    source_id: 'BBC-AMHARIC',
    source_name: 'BBC Amharic',
    status: 'active',
    base_url: 'https://feeds.bbci.co.uk/amharic/rss.xml',
    source_type: 'Local Language RSS',
    category: 'Local_Language',
    coverage: 'Ethiopia',
    priority: 2,
    auth_type: 'None',
    data_format: 'RSS',
  },
  // NEW: BBC Arabic for North Africa
  {
    source_id: 'BBC-ARABIC',
    source_name: 'BBC Arabic',
    status: 'active',
    base_url: 'https://feeds.bbci.co.uk/arabic/rss.xml',
    source_type: 'Local Language RSS',
    category: 'Local_Language',
    coverage: 'Egypt, Sudan, Libya, Tunisia, Algeria, Morocco',
    priority: 2,
    auth_type: 'None',
    data_format: 'RSS',
  },
  // NEW: RFI French Africa
  {
    source_id: 'RFI-AFRIQUE',
    source_name: 'RFI Afrique (French)',
    status: 'active',
    base_url: 'https://www.rfi.fr/fr/afrique/rss',
    source_type: 'Local Language RSS',
    category: 'Local_Language',
    coverage: 'Francophone Africa (20+ countries)',
    priority: 2,
    auth_type: 'None',
    data_format: 'RSS',
  },
  // NEW: VOA Portuguese for Lusophone Africa
  {
    source_id: 'VOA-PORTUGUESE',
    source_name: 'VOA Português África',
    status: 'active',
    base_url: 'https://www.voaportugues.com/api/z_pqyepp_qyi',
    source_type: 'Local Language RSS',
    category: 'Local_Language',
    coverage: 'Angola, Mozambique, Guinea-Bissau, Cabo Verde, São Tomé',
    priority: 2,
    auth_type: 'None',
    data_format: 'RSS',
  },
  // NEW: Al Jazeera Arabic for North/East Africa
  {
    source_id: 'ALJAZEERA-ARABIC',
    source_name: 'Al Jazeera Arabic',
    status: 'active',
    base_url: 'https://www.aljazeera.net/aljazeerarss/a7c186be-1baa-4bd4-9d80-a84db769f779/73d0e1b4-532f-45ef-b135-bfdff8b8cab9',
    source_type: 'Local Language RSS',
    category: 'Local_Language',
    coverage: 'North Africa, Sudan, Somalia, Djibouti',
    priority: 2,
    auth_type: 'None',
    data_format: 'RSS',
  },
  {
    source_id: 'ALLAFRICA',
    source_name: 'AllAfrica News',
    status: 'active',
    base_url: 'https://allafrica.com/tools/headlines/v2/xml/',
    source_type: 'News Aggregator',
    category: 'Aggregator',
    coverage: 'Africa',
    priority: 2,
    auth_type: 'None',
    data_format: 'RSS',
  },
  {
    source_id: 'AFRICANEWS',
    source_name: 'Africanews',
    status: 'active',
    base_url: 'https://www.africanews.com/feed/rss/',
    source_type: 'Pan-African News',
    category: 'Media',
    coverage: 'Africa',
    priority: 2,
    auth_type: 'None',
    data_format: 'RSS',
  },
  
  // =====================================================
  // TIER 2 - Local Newspapers
  // =====================================================
  {
    source_id: 'VANGUARD-NG',
    source_name: 'Vanguard Nigeria',
    status: 'active',
    base_url: 'https://www.vanguardngr.com/category/health/feed/',
    source_type: 'Local Newspaper',
    category: 'Local_Media',
    coverage: 'Nigeria',
    priority: 2,
    auth_type: 'None',
    data_format: 'RSS',
  },
  {
    source_id: 'NATION-KE',
    source_name: 'Daily Nation Kenya',
    status: 'active',
    base_url: 'https://nation.africa/kenya/health/rss',
    source_type: 'Local Newspaper',
    category: 'Local_Media',
    coverage: 'Kenya',
    priority: 2,
    auth_type: 'None',
    data_format: 'RSS',
  },
  {
    source_id: 'NEWS24-SA',
    source_name: 'News24 South Africa',
    status: 'active',
    base_url: 'https://feeds.news24.com/articles/news24/SouthAfrica/rss',
    source_type: 'Local Newspaper',
    category: 'Local_Media',
    coverage: 'South Africa',
    priority: 2,
    auth_type: 'None',
    data_format: 'RSS',
  },
  {
    source_id: 'REPORTER-ETH',
    source_name: 'The Reporter Ethiopia',
    status: 'active',
    base_url: 'https://www.thereporterethiopia.com/feed/',
    source_type: 'Local Newspaper',
    category: 'Local_Media',
    coverage: 'Ethiopia',
    priority: 2,
    auth_type: 'None',
    data_format: 'RSS',
  },
  // NEW: Jeune Afrique (French - influential)
  {
    source_id: 'JEUNE-AFRIQUE',
    source_name: 'Jeune Afrique',
    status: 'active',
    base_url: 'https://www.jeuneafrique.com/feed/',
    source_type: 'Pan-African Magazine',
    category: 'Local_Media',
    coverage: 'Francophone Africa',
    priority: 2,
    auth_type: 'None',
    data_format: 'RSS',
  },
  // NEW: Le Monde Afrique
  {
    source_id: 'LEMONDE-AFRIQUE',
    source_name: 'Le Monde Afrique',
    status: 'active',
    base_url: 'https://www.lemonde.fr/afrique/rss_full.xml',
    source_type: 'International French',
    category: 'Local_Media',
    coverage: 'Francophone Africa',
    priority: 2,
    auth_type: 'None',
    data_format: 'RSS',
  },
  // NEW: Jornal de Angola
  {
    source_id: 'JORNAL-ANGOLA',
    source_name: 'Jornal de Angola',
    status: 'active',
    base_url: 'https://www.jornaldeangola.ao/ao/rss/',
    source_type: 'Local Newspaper',
    category: 'Local_Media',
    coverage: 'Angola',
    priority: 2,
    auth_type: 'None',
    data_format: 'RSS',
  },
  // NEW: O País Moçambique
  {
    source_id: 'OPAIS-MOZ',
    source_name: 'O País Moçambique',
    status: 'active',
    base_url: 'https://opais.co.mz/feed/',
    source_type: 'Local Newspaper',
    category: 'Local_Media',
    coverage: 'Mozambique',
    priority: 2,
    auth_type: 'None',
    data_format: 'RSS',
  },
  
  // =====================================================
  // TIER 2 - Nigerian TV & Internet News
  // =====================================================
  {
    source_id: 'CHANNELS-TV',
    source_name: 'Channels Television',
    status: 'active',
    base_url: 'https://www.channelstv.com/feed/',
    source_type: 'TV/Internet News',
    category: 'Local_Media',
    coverage: 'Nigeria',
    priority: 2,
    auth_type: 'None',
    data_format: 'RSS',
  },
  {
    source_id: 'ARISE-TV',
    source_name: 'Arise News',
    status: 'active',
    base_url: 'https://www.arise.tv/feed/',
    source_type: 'TV/Internet News',
    category: 'Local_Media',
    coverage: 'Nigeria, Pan-African',
    priority: 2,
    auth_type: 'None',
    data_format: 'RSS',
  },
  {
    source_id: 'PUNCH-NG',
    source_name: 'The Punch Nigeria',
    status: 'active',
    base_url: 'https://punchng.com/feed/',
    source_type: 'Local Newspaper',
    category: 'Local_Media',
    coverage: 'Nigeria',
    priority: 2,
    auth_type: 'None',
    data_format: 'RSS',
  },
  {
    source_id: 'GUARDIAN-NG',
    source_name: 'The Guardian Nigeria',
    status: 'active',
    base_url: 'https://guardian.ng/feed/',
    source_type: 'Local Newspaper',
    category: 'Local_Media',
    coverage: 'Nigeria',
    priority: 2,
    auth_type: 'None',
    data_format: 'RSS',
  },
  {
    source_id: 'THISDAY',
    source_name: 'ThisDay Live',
    status: 'active',
    base_url: 'https://www.thisdaylive.com/feed/',
    source_type: 'Local Newspaper',
    category: 'Local_Media',
    coverage: 'Nigeria',
    priority: 2,
    auth_type: 'None',
    data_format: 'RSS',
  },
  {
    source_id: 'PREMIUM-TIMES',
    source_name: 'Premium Times',
    status: 'active',
    base_url: 'https://www.premiumtimesng.com/feed',
    source_type: 'Investigative News',
    category: 'Local_Media',
    coverage: 'Nigeria',
    priority: 2,
    auth_type: 'None',
    data_format: 'RSS',
  },
  {
    source_id: 'DAILY-TRUST',
    source_name: 'Daily Trust',
    status: 'active',
    base_url: 'https://dailytrust.com/feed/',
    source_type: 'Local Newspaper',
    category: 'Local_Media',
    coverage: 'Nigeria (North focus)',
    priority: 2,
    auth_type: 'None',
    data_format: 'RSS',
  },
  {
    source_id: 'LEADERSHIP-NG',
    source_name: 'Leadership Newspaper',
    status: 'active',
    base_url: 'https://leadership.ng/feed/',
    source_type: 'Local Newspaper',
    category: 'Local_Media',
    coverage: 'Nigeria',
    priority: 2,
    auth_type: 'None',
    data_format: 'RSS',
  },
  
  // =====================================================
  // TIER 2 - Other African TV/Internet News
  // =====================================================
  {
    source_id: 'CITIZEN-KE',
    source_name: 'Citizen TV Kenya',
    status: 'active',
    base_url: 'https://www.citizen.digital/feed',
    source_type: 'TV/Internet News',
    category: 'Local_Media',
    coverage: 'Kenya',
    priority: 2,
    auth_type: 'None',
    data_format: 'RSS',
  },
  {
    source_id: 'KTN-KE',
    source_name: 'KTN News Kenya',
    status: 'active',
    base_url: 'https://www.standardmedia.co.ke/rss/headlines.php',
    source_type: 'TV/Internet News',
    category: 'Local_Media',
    coverage: 'Kenya',
    priority: 2,
    auth_type: 'None',
    data_format: 'RSS',
  },
  {
    source_id: 'SABC-ZA',
    source_name: 'SABC News',
    status: 'active',
    base_url: 'https://www.sabcnews.com/sabcnews/feed/',
    source_type: 'TV/Internet News',
    category: 'Local_Media',
    coverage: 'South Africa',
    priority: 2,
    auth_type: 'None',
    data_format: 'RSS',
  },
  {
    source_id: 'ENATV-ETH',
    source_name: 'ENA (Ethiopian News Agency)',
    status: 'active',
    base_url: 'https://www.ena.et/en/feed/',
    source_type: 'Official News Agency',
    category: 'Local_Media',
    coverage: 'Ethiopia',
    priority: 2,
    auth_type: 'None',
    data_format: 'RSS',
  },
  {
    source_id: 'GNA-GH',
    source_name: 'Ghana News Agency',
    status: 'active',
    base_url: 'https://gna.org.gh/feed/',
    source_type: 'Official News Agency',
    category: 'Local_Media',
    coverage: 'Ghana',
    priority: 2,
    auth_type: 'None',
    data_format: 'RSS',
  },
  
  // =====================================================
  // TIER 3 - Citizen Journalism & Blogs
  // =====================================================
  {
    source_id: 'SAHARA-REPORTERS',
    source_name: 'Sahara Reporters',
    status: 'active',
    base_url: 'https://saharareporters.com/articles/rss-feed',
    source_type: 'Citizen Journalism',
    category: 'Community',
    coverage: 'Nigeria',
    priority: 3,
    auth_type: 'None',
    data_format: 'RSS',
  },
  {
    source_id: 'NAIRALAND',
    source_name: 'Nairaland Forum',
    status: 'active',
    base_url: 'https://www.nairaland.com/feed',
    source_type: 'Community Forum',
    category: 'Community',
    coverage: 'Nigeria',
    priority: 3,
    auth_type: 'None',
    data_format: 'RSS',
  },
  {
    source_id: 'BELLANAIJA',
    source_name: 'BellaNaija',
    status: 'active',
    base_url: 'https://www.bellanaija.com/feed/',
    source_type: 'Lifestyle Blog',
    category: 'Community',
    coverage: 'Nigeria, Pan-African',
    priority: 3,
    auth_type: 'None',
    data_format: 'RSS',
  },
  {
    source_id: 'REDDIT-AFRICA',
    source_name: 'Reddit r/Africa',
    status: 'active',
    base_url: 'https://www.reddit.com/r/africa/search.json',
    source_type: 'Community Forum',
    category: 'Community',
    coverage: 'Africa',
    priority: 3,
    auth_type: 'None',
    data_format: 'JSON',
  },
  {
    source_id: 'REDDIT-NIGERIA',
    source_name: 'Reddit r/Nigeria',
    status: 'active',
    base_url: 'https://www.reddit.com/r/Nigeria/search.json',
    source_type: 'Community Forum',
    category: 'Community',
    coverage: 'Nigeria',
    priority: 3,
    auth_type: 'None',
    data_format: 'JSON',
  },
  {
    source_id: 'MASTODON-HEALTH',
    source_name: 'Mastodon Health Hashtags',
    status: 'active',
    base_url: 'https://mastodon.social/api/v1/timelines/tag/',
    source_type: 'Social Media',
    category: 'Community',
    coverage: 'Global (Africa filter)',
    priority: 3,
    auth_type: 'None',
    data_format: 'JSON',
  },
  {
    source_id: 'LEMMY-AFRICA',
    source_name: 'Lemmy Africa Communities',
    status: 'active',
    base_url: 'https://lemmy.world/api/v3/post/list',
    source_type: 'Community Forum',
    category: 'Community',
    coverage: 'Africa',
    priority: 3,
    auth_type: 'None',
    data_format: 'JSON',
  },
];

// Mapbox token (publishable - safe for client-side)
export const MAPBOX_TOKEN = 'pk.eyJ1IjoiYWthbmltbzEiLCJhIjoiY2x4czNxbjU2MWM2eTJqc2gwNGIwaWhkMSJ9.jSwZdyaPa1dOHepNU5P71g';

// WHO Data source
export const WHO_DATA_URL = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vS-8N_ALP4IX8k7sFPRzdeALWNNeYpOMmGpbVC3V-nfAyvHsa0ZB6I2YFgONi4McA';

export type Priority = keyof typeof PRIORITIES;
export type SourceTier = keyof typeof SOURCE_TIERS;
export type DiseaseCategory = keyof typeof DISEASE_CATEGORIES;
export type SignalStatus = keyof typeof SIGNAL_STATUSES;
