import type { Signal } from '@/hooks/useSignals';

export const DEMO_SIGNALS: Signal[] = [
  {
    id: 'sig-demo-001',
    created_at: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    disease_name: 'Mpox (Clade Ib)',
    disease_category: 'zoonotic',
    priority: 'P1',
    status: 'validated',
    location_country: 'DR Congo',
    location_country_iso: 'COD',
    location_admin1: 'South Kivu',
    location_admin2: 'Kamituga Health Zone',
    location_locality: 'Kamituga Mining District',
    location_lat: -3.0614,
    location_lng: 28.1783,
    reported_cases: 42,
    reported_deaths: 3,
    confidence_score: 94,
    lingua_fidelity_score: 89,
    cross_border_risk: true,
    seasonal_pattern_match: false,
    signal_type: 'outbreak',
    source_name: 'Ministère de la Santé Publique RDC',
    source_tier: 'tier_1',
    source_type: 'Official MOH Epidemiological Bulletin',
    source_url: 'https://who.int/emergencies/mpox-drc',
    source_id: 'RDC-MOH-2026-WK37',
    source_timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    original_language: 'fr',
    original_script: 'Latin',
    original_text: 'Alerte sanitaire: Recrudescence rapide de cas suspects de Mpox avec lésions génitales sévères à Kamituga. Trois décès confirmés en pédiatrie.',
    translated_text: 'Health alert: Rapid resurgence of suspected Mpox cases with severe genital lesions in Kamituga. Three confirmed pediatric deaths.',
    translation_confidence: 96,
    affected_population: 'Artisanal mining community and local healthcare workers',
    analyst_notes: '[AI TRIAGE] High-threat cluster of Clade Ib Mpox. Cross-border transmission risk elevated due to transport corridor to Rwanda and Burundi.',
    corroborating_signals: ['RDC-RAD-891', 'PROM-2026-COD'],
    ingestion_source: 'who-afro-epifeed',
    raw_payload: null,
    triaged_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    triaged_by: 'system-ai-analyst',
    validated_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    validated_by: 'test-user-admin-001',
  },
  {
    id: 'sig-demo-002',
    created_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    disease_name: 'Marburg Virus Disease',
    disease_category: 'vhf',
    priority: 'P1',
    status: 'validated',
    location_country: 'Rwanda',
    location_country_iso: 'RWA',
    location_admin1: 'Kigali',
    location_admin2: 'Gasabo',
    location_locality: 'King Faisal Hospital Area',
    location_lat: -1.9441,
    location_lng: 30.0619,
    reported_cases: 6,
    reported_deaths: 2,
    confidence_score: 98,
    lingua_fidelity_score: 92,
    cross_border_risk: true,
    seasonal_pattern_match: false,
    signal_type: 'vhf_alert',
    source_name: 'Rwanda Biomedical Centre (RBC)',
    source_tier: 'tier_1',
    source_type: 'National Surveillance Flash Report',
    source_url: 'https://rbc.gov.rw',
    source_id: 'RBC-MVD-0916',
    source_timestamp: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    original_language: 'rw',
    original_script: 'Latin',
    original_text: 'Itangazo ryihuse: Abantu batanu bagaragaje ibimenyetso by’umuriro utera kuva amaraso (Marburg). Abashinzwe ubuzima batangiye gushakisha abahuye nabo.',
    translated_text: 'Urgent notice: Five individuals identified with viral hemorrhagic symptoms (Marburg). Rapid response teams initiated active contact tracing.',
    translation_confidence: 94,
    affected_population: 'Hospital staff and close household contacts',
    analyst_notes: '[AI TRIAGE] Confirmed Filovirus cluster. Level 3 containment activated across sentinel tertiary treatment facilities.',
    corroborating_signals: ['RBC-CT-004'],
    ingestion_source: 'rbc-surveillance',
    raw_payload: null,
    triaged_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    triaged_by: 'system-ai-analyst',
    validated_at: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    validated_by: 'test-user-admin-001',
  },
  {
    id: 'sig-demo-003',
    created_at: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    disease_name: 'Cholera (Vibrio cholerae O1)',
    disease_category: 'enteric',
    priority: 'P2',
    status: 'new',
    location_country: 'Zambia',
    location_country_iso: 'ZMB',
    location_admin1: 'Lusaka',
    location_admin2: 'Kanyama Compound',
    location_locality: 'Ward 10 Peri-urban settlement',
    location_lat: -15.4216,
    location_lng: 28.2573,
    reported_cases: 68,
    reported_deaths: 4,
    confidence_score: 88,
    lingua_fidelity_score: 85,
    cross_border_risk: false,
    seasonal_pattern_match: true,
    signal_type: 'waterborne',
    source_name: 'Zambia National Public Health Institute (ZNPHI)',
    source_tier: 'tier_1',
    source_type: 'Epidemic Situation Report',
    source_url: 'https://znphi.co.zm',
    source_id: 'ZNPHI-CHOL-41',
    source_timestamp: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    original_language: 'en',
    original_script: 'Latin',
    original_text: 'Surge in acute watery diarrhea admissions at Kanyama CTC following flash floods. Water testing shows high contamination in shallow wells.',
    translated_text: 'Surge in acute watery diarrhea admissions at Kanyama CTC following flash floods. Water testing shows high contamination in shallow wells.',
    translation_confidence: 100,
    affected_population: 'Dense informal settlement residents, high child vulnerability',
    analyst_notes: '[PENDING TRIAGE] Oral cholera vaccine stockpile deployment recommended. Water treatment chlorination points being deployed.',
    corroborating_signals: [],
    ingestion_source: 'znphi-bulletin',
    raw_payload: null,
    triaged_at: null,
    triaged_by: null,
    validated_at: null,
    validated_by: null,
  },
  {
    id: 'sig-demo-004',
    created_at: new Date(Date.now() - 75 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 75 * 60 * 1000).toISOString(),
    disease_name: 'Dengue Fever (DENV-2)',
    disease_category: 'vector_borne',
    priority: 'P2',
    status: 'new',
    location_country: 'Mali',
    location_country_iso: 'MLI',
    location_admin1: 'Bamako',
    location_admin2: 'Commune IV',
    location_locality: 'Lafiabougou',
    location_lat: 12.6392,
    location_lng: -8.0029,
    reported_cases: 85,
    reported_deaths: 1,
    confidence_score: 82,
    lingua_fidelity_score: 87,
    cross_border_risk: false,
    seasonal_pattern_match: true,
    signal_type: 'vector_surge',
    source_name: 'Institut National de Santé Publique Mali',
    source_tier: 'tier_2',
    source_type: 'Clinical Laboratory Aggregate',
    source_url: 'https://sante.gov.ml',
    source_id: 'INSP-DEN-2026-08',
    source_timestamp: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    original_language: 'fr',
    original_script: 'Latin',
    original_text: 'Augmentation sensible des cas de fièvres aiguës fébriles avec thrombopénie marquée à Bamako suite aux pluies récentes.',
    translated_text: 'Significant increase in acute febrile illness with marked thrombocytopenia in Bamako following recent rains.',
    translation_confidence: 93,
    affected_population: 'Urban population in areas with standing rainwater containers',
    analyst_notes: '[PENDING TRIAGE] High vector density of Aedes aegypti recorded across district monitoring traps.',
    corroborating_signals: [],
    ingestion_source: 'afro-media-feed',
    raw_payload: null,
    triaged_at: null,
    triaged_by: null,
    validated_at: null,
    validated_by: null,
  },
  {
    id: 'sig-demo-005',
    created_at: new Date(Date.now() - 110 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 110 * 60 * 1000).toISOString(),
    disease_name: 'Lassa Fever',
    disease_category: 'vhf',
    priority: 'P1',
    status: 'validated',
    location_country: 'Nigeria',
    location_country_iso: 'NGA',
    location_admin1: 'Ondo State',
    location_admin2: 'Owo LGA',
    location_locality: 'Federal Medical Centre Owo',
    location_lat: 7.1989,
    location_lng: 5.5868,
    reported_cases: 19,
    reported_deaths: 5,
    confidence_score: 95,
    lingua_fidelity_score: 91,
    cross_border_risk: false,
    seasonal_pattern_match: true,
    signal_type: 'endemic_surge',
    source_name: 'Nigeria Centre for Disease Control (NCDC)',
    source_tier: 'tier_1',
    source_type: 'Weekly Epidemiological Report',
    source_url: 'https://ncdc.gov.ng',
    source_id: 'NCDC-LF-WK36',
    source_timestamp: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    original_language: 'en',
    original_script: 'Latin',
    original_text: 'Case fatality rate stands at 26.3% in FMC Owo treatment center. Ribavirin supplies requested from national emergency stockpile.',
    translated_text: 'Case fatality rate stands at 26.3% in FMC Owo treatment center. Ribavirin supplies requested from national emergency stockpile.',
    translation_confidence: 100,
    affected_population: 'Rural agricultural communities and healthcare personnel',
    analyst_notes: '[AI TRIAGE] Classical seasonal peak driven by dry season Mastomys rodent migration into food stores.',
    corroborating_signals: ['NCDC-LF-012'],
    ingestion_source: 'ncdc-api',
    raw_payload: null,
    triaged_at: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    triaged_by: 'system-ai-analyst',
    validated_at: new Date(Date.now() - 80 * 60 * 1000).toISOString(),
    validated_by: 'test-user-admin-001',
  },
  {
    id: 'sig-demo-006',
    created_at: new Date(Date.now() - 150 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 150 * 60 * 1000).toISOString(),
    disease_name: 'Measles Outbreak',
    disease_category: 'vaccine_preventable',
    priority: 'P3',
    status: 'triaged',
    location_country: 'Chad',
    location_country_iso: 'TCD',
    location_admin1: 'Ouaddaï',
    location_admin2: 'Abéché',
    location_locality: 'Eastern Transit Camp',
    location_lat: 13.8292,
    location_lng: 20.8322,
    reported_cases: 110,
    reported_deaths: 2,
    confidence_score: 79,
    lingua_fidelity_score: 82,
    cross_border_risk: true,
    seasonal_pattern_match: false,
    signal_type: 'vaccine_gap',
    source_name: 'UNHCR Health Partner Network',
    source_tier: 'tier_2',
    source_type: 'Field Health Survey',
    source_url: 'https://unhcr.org',
    source_id: 'UNHCR-TCD-MSL-02',
    source_timestamp: new Date(Date.now() - 180 * 60 * 1000).toISOString(),
    original_language: 'ar',
    original_script: 'Arabic',
    original_text: 'تسجيل أكثر من مئة حالة حصبة بين الأطفال الوافدين الجدد في مخيمات عبيد وأدري نتيجة تدني مستويات التطعيم الروتيني.',
    translated_text: 'Over 100 measles cases registered among newly arriving children in transit camps due to disrupted routine immunization.',
    translation_confidence: 91,
    affected_population: 'Displaced populations and host community under-5 children',
    analyst_notes: '[TRIAGED] Supplementary immunization campaign planned in coordination with WHO emergency hub.',
    corroborating_signals: [],
    ingestion_source: 'unhcr-cluster',
    raw_payload: null,
    triaged_at: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    triaged_by: 'system-ai-analyst',
    validated_at: null,
    validated_by: null,
  },
  {
    id: 'sig-demo-007',
    created_at: new Date(Date.now() - 200 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 200 * 60 * 1000).toISOString(),
    disease_name: 'Meningococcal Meningitis (Serogroup C)',
    disease_category: 'respiratory',
    priority: 'P2',
    status: 'validated',
    location_country: 'Niger',
    location_country_iso: 'NER',
    location_admin1: 'Zinder',
    location_admin2: 'Mirriah',
    location_locality: 'District Sanitaire de Mirriah',
    location_lat: 13.7167,
    location_lng: 9.15,
    reported_cases: 74,
    reported_deaths: 9,
    confidence_score: 91,
    lingua_fidelity_score: 86,
    cross_border_risk: true,
    seasonal_pattern_match: true,
    signal_type: 'meningitis_belt',
    source_name: 'Ministère de la Santé Publique du Niger',
    source_tier: 'tier_1',
    source_type: 'Epidemic Threshold Alert',
    source_url: 'https://santepublique.ne',
    source_id: 'NER-MOH-MEN-2026',
    source_timestamp: new Date(Date.now() - 240 * 60 * 1000).toISOString(),
    original_language: 'ha',
    original_script: 'Latin',
    original_text: 'Rahotannin kiwon lafiya sun nuna bullar cutar sankarau a gundumar Mirriah. An bayar da shawarar gudanar da allurar riga-kafi cikin gaggawa.',
    translated_text: 'Health reports indicate an epidemic wave of meningitis in Mirriah district. Urgent reactive vaccination recommended.',
    translation_confidence: 92,
    affected_population: 'School-age children and young adults in dry harmattan conditions',
    analyst_notes: '[AI TRIAGE] Epidemic threshold crossed (10 cases / 100,000 / week). ICG vaccine dossier submitted.',
    corroborating_signals: [],
    ingestion_source: 'who-afro-meningitis-network',
    raw_payload: null,
    triaged_at: new Date(Date.now() - 180 * 60 * 1000).toISOString(),
    triaged_by: 'system-ai-analyst',
    validated_at: new Date(Date.now() - 160 * 60 * 1000).toISOString(),
    validated_by: 'test-user-admin-001',
  }
];

export function filterDemoSignals(options: {
  priority?: ('P1' | 'P2' | 'P3' | 'P4')[];
  status?: ('new' | 'triaged' | 'validated' | 'dismissed')[];
  country?: string;
  disease?: string;
  limit?: number;
}): Signal[] {
  let list = [...DEMO_SIGNALS];

  if (options.priority && options.priority.length > 0) {
    list = list.filter(s => options.priority!.includes(s.priority as any));
  }

  if (options.status && options.status.length > 0) {
    list = list.filter(s => options.status!.includes(s.status as any));
  }

  if (options.country) {
    list = list.filter(s => s.location_country.toLowerCase().includes(options.country!.toLowerCase()));
  }

  if (options.disease) {
    list = list.filter(s => (s.disease_name || '').toLowerCase().includes(options.disease!.toLowerCase()));
  }

  if (options.limit && options.limit > 0) {
    list = list.slice(0, options.limit);
  }

  return list;
}
